name: Deploy MkDocs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Preparar pasta docs
        run: |
          mkdir -p docs
          rsync -av --exclude='docs' --exclude='.github' --exclude='mkdocs.yml' --exclude='index.html' --exclude='.nojekyll' --exclude='.git' . docs/
          find docs/ -name "*.md" -exec sed -i '/^icon:/d' {} \;
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
